name: Apexyx Sovereign OMEGA-FORGE
on: [push]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
  workflow_dispatch:
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.10'}
  workflow_dispatch:
      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-REBORN-V1
      - name: System Align
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev libssl-dev python3-dev zip unzip openjdk-17-jdk wget zlib1g-dev autoconf libtool pkg-config cmake libstdc++6 lld
      - name: Build Tools
        run: pip install --upgrade pip "buildozer>=1.5.0" "Cython==0.29.33" virtualenv
      - name: Forge APK
        run: buildozer -v android debug
      - name: Upload Sovereign APK
        uses: actions/upload-artifact@v4
        with: {name: Apexyx-Sovereign-FINAL, path: ./**/*.apk}
